# Generated by Django 6.0.3 on 2026-05-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='heading',
            field=models.CharField(default='General Service', max_length=150),
        ),
    ]
