# Generated by Django 6.0.3 on 2026-05-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_price_service_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='services',
        ),
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
