# Generated by Django 6.0.3 on 2026-05-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_hospital_services_hospital_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='phone',
        ),
    ]
