from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('logout/', views.admin_logout, name='logout'),
    path('services/', views.services, name='services'),
    path('add-service/', views.add_service, name='add_service'),
    path('edit-service/<int:service_id>/', views.edit_service, name='edit_service'),
    path('delete-service/<int:service_id>/', views.delete_service, name='delete_service'),
    path('manage-services/', views.manage_services, name='manage_services'),
    path('hospital/', views.hospital_list, name='hospital_list'),
    path('add-hospital/', views.add_hospital, name='add_hospital'),
    path('edit-hospital/<int:hospital_id>/', views.edit_hospital, name='edit_hospital'),
    path('delete-hospital/<int:hospital_id>/', views.delete_hospital, name='delete_hospital'),
    path('manage-hospitals/', views.manage_hospitals, name='manage_hospitals'),
    path('contact/', views.contact_page, name='contact_page'),
    path('contact/save/', views.contact_save, name='contact_save'),
    path('manage-contacts/', views.manage_contacts, name='manage_contacts'),
    path('delete-contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('manage-slider/', views.manage_slider, name='manage_slider'),
    path('add-slider/', views.add_slider, name='add_slider'),
    path('edit-slider/<int:slide_id>/', views.edit_slider, name='edit_slider'),
    path('delete-slider/<int:slide_id>/', views.delete_slider, name='delete_slider'),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("profile/", views.profile_view, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/change-password/", views.change_password, name="change_password"),\
    path('manage-home-content/',views.manage_home_content,name='manage_home_content'),
    path('add-home-content/',views.add_home_content,name='add_home_content'),
    path('edit-home-content/<int:id>/',views.edit_home_content,name='edit_home_content'),
    path('delete-home-content/<int:id>/',views.delete_home_content,name='delete_home_content'),
    path('manage-about/', views.manage_about, name='manage_about'),
    path('add-about/', views.add_about, name='add_about'),
    path('edit-about/<int:id>/', views.edit_about, name='edit_about'),
    path('delete-about/<int:id>/', views.delete_about, name='delete_about'),
]